logging:
  file:
    name: greenuniv.log
    path: ${user.home}/greenuniv/logs/
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug
    root: info
    sql: debug
server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: GreenUniv
    version: 0.0.2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/green_univ
    username: root
  devtools:
    livereload:
      enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
